apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hjq2xvrlt-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:e7484242cb2da50f38c4e87583ea68acf9507cda@sha256:48458d7f7b4d12ee0a9d82a924354cd40bd69ff83cec8874821c79c8bcb6f71d
          name: container-image
